- name: Configure EtherChannel on physical interfaces
  cisco.ios.ios_config:
    lines:
      - "interface {{ item }}"
      - "channel-group {{ etherchannel_group }} mode desirable"
  loop: "{{ etherchannel_ports }}"