---
- name: Configure EtherChannel on physical interfaces
  cisco.ios.ios_config:
    parents: "interface {{ item }}"
    lines:
      - "channel-group {{ etherchannel_group }} mode desirable"
  loop: "{{ etherchannel_ports }}"


  