---
- name: Install ansible-pylibssh
  hosts: localhost
  gather_facts: no
  become_method: su
  become_user: root
  tasks:
    - name: Install ansible-pylibssh
      pip:
        name: ansible-pylibssh
        state: present
