---
- name: Configure production switches
  hosts: production_switches
  gather_facts: no
  roles:
#    - base_config
#    - vlan_config
#    - access_config
#    - trunk_config
#    - stp_config
    - backup_to_nextcloud

#  tasks:
#    - name: Save production switches configuration  
#      cisco.ios.ios_config:
#        save_when: modified

- name: Configure routers
  hosts: routers
  gather_facts: no
  roles:
#    - base_config
#    - subint_config
#    - ospf_config
#    - hsrp_config
    - backup_to_nextcloud
#  tasks:
#    - name: Save production switches configuration  
#      cisco.ios.ios_config:
#        save_when: modified  

