---
- name: Configure trunk on trunks
  cisco.ios.ios_config:
    lines:
      - "interface {{ item.name }}"
      - "switchport trunk encapsulation dot1q"
      - "switchport mode trunk"
      - "switchport trunk allowed vlan add {{ trunk_vlans|join(',') }}"
      - "no shutdown"
  loop: "{{ trunk_ports }}"

  
