---
- name: Get current configuration
  cisco.ios.ios_command:
    commands:
      - show running-config
  register: running_conf

- name: Save configuration to a file
  local_action:
    module: copy
    content: "{{ running_conf.stdout[0] }}"
    dest: "/tmp/cisco_backup_{{ inventory_hostname }}.cfg"

- name: Set date
  set_fact:
    date_stamp: "{{ '%Y%m%d_%H:%M:%S' | strftime() }}"  

- name: Run backup script
  become: false
  args:
    chdir: "{{ role_path }}/files"
  environment:
    NEXTCLOUD_URL: "http://10.0.41.21/"
    NEXTCLOUD_USERNAME: "nextclouduser"
    NEXTCLOUD_PASSWORD: "{{ nextcloud_password }}"
  command: "python3 backup.py /tmp/cisco_backup_{{ inventory_hostname }}.cfg Documents/{{ inventory_hostname }}/cisco_backup_{{ inventory_hostname }}_{{ date_stamp }}.cfg"

