---
- name: Configure bureau access ports
  cisco.ios.ios_config:
    lines:
      - "interface {{ item.name }}"
      - "switchport mode access"
      - "switchport access vlan {{ vlan_bureau_id }}"
      - "no shutdown"
  loop: "{{ bureau_ports }}"

- name: Configure IT access ports
  cisco.ios.ios_config:
    lines:
      - "interface {{ item.name }}"
      - "switchport mode access"
      - "switchport access vlan {{ vlan_it_id }}"
      - "no shutdown"
  loop: "{{ it_ports }}"

- name: Configure server access ports
  cisco.ios.ios_config:
    lines:
      - "interface {{ item.name }}"
      - "switchport mode access"
      - "switchport access vlan {{ vlan_servers_id }}"
      - "no shutdown"
  loop: "{{ servers_ports }}"

