---
- name: Configure access ports
  cisco.ios.ios_config:
    lines:
      - "interface {{ item.1.name }}"
      - "switchport mode access"
      - "switchport access vlan {{ item.0.vlan_id }}"
      - "no shutdown"
  loop: "{{ access_config | subelements('ports') }}"
