interfaces:
  - name: e0/0
    subifs:
      - { vlan: 20 }
      - { vlan: 30 }
  - name: e0/1
    subifs:
      - { vlan: 50 }

virtual_ip_last_octet: 254

ospf_process_id: 1

ospf_networks:
  - { network: "10.0.20.0", wildcard: "0.0.0.255", area: "0" }
  - { network: "10.0.30.0", wildcard: "0.0.0.255", area: "0" }
  - { network: "10.0.50.0", wildcard: "0.0.0.255", area: "0" }

  